package com.example.knowledgecollector.infrastructure.externalsystem;
import com.example.knowledgecollector.application.exception.ResourceNotFoundException;import com.example.knowledgecollector.application.externalsystem.*;import org.springframework.jdbc.core.simple.JdbcClient;import org.springframework.stereotype.Repository;import java.sql.*;import java.time.OffsetDateTime;import java.util.*;
@Repository public class JdbcExternalSystemGateway implements ExternalSystemGateway {
 private final JdbcClient jdbc;public JdbcExternalSystemGateway(JdbcClient jdbc){this.jdbc=jdbc;}public List<ExternalSystemView> list(){return jdbc.sql("select * from external_system order by sort_order,id").query(this::view).list();}public ExternalSystemView get(long id){return jdbc.sql("select * from external_system where id=:id").param("id",id).query(this::view).optional().orElseThrow(()->new ResourceNotFoundException("第三方系统不存在："+id));}
 public long create(ExternalSystemCommand c){OffsetDateTime n=OffsetDateTime.now();jdbc.sql("insert into external_system(system_code,system_name,system_type,description,icon,access_url,health_url,open_mode,enabled,allowed_role,sort_order,created_at,updated_at) values(:code,:name,:type,:desc,:icon,:access,:health,:mode,:enabled,:role,:sort,:now,:now)").param("code",c.code()).param("name",c.name()).param("type",c.type()).param("desc",c.description()).param("icon",c.icon()).param("access",c.accessUrl()).param("health",c.healthUrl()).param("mode",c.openMode()).param("enabled",c.enabled()).param("role",c.allowedRole()).param("sort",c.sortOrder()).param("now",n).update();return jdbc.sql("select id from external_system where system_code=:code").param("code",c.code()).query(Long.class).single();}
 public ExternalSystemView update(long id,ExternalSystemCommand c){int n=jdbc.sql("update external_system set system_code=:code,system_name=:name,system_type=:type,description=:desc,icon=:icon,access_url=:access,health_url=:health,open_mode=:mode,enabled=:enabled,allowed_role=:role,sort_order=:sort,health_status=case when :enabled=false then 'DISABLED' else health_status end,updated_at=:now where id=:id").param("code",c.code()).param("name",c.name()).param("type",c.type()).param("desc",c.description()).param("icon",c.icon()).param("access",c.accessUrl()).param("health",c.healthUrl()).param("mode",c.openMode()).param("enabled",c.enabled()).param("role",c.allowedRole()).param("sort",c.sortOrder()).param("now",OffsetDateTime.now()).param("id",id).update();if(n==0)throw new ResourceNotFoundException("第三方系统不存在："+id);return get(id);}public ExternalSystemView setEnabled(long id,boolean e){var v=get(id);return update(id,new ExternalSystemCommand(v.code(),v.name(),v.type(),v.description(),v.icon(),v.accessUrl(),v.healthUrl(),v.openMode(),e,v.allowedRole(),v.sortOrder()));}
 public void updateHealth(long id,String status,OffsetDateTime checked,OffsetDateTime success,String error){jdbc.sql("update external_system set health_status=:s,last_checked_at=:c,last_success_at=coalesce(:ok,last_success_at),last_error=:e,updated_at=:c where id=:id").param("s",status).param("c",checked).param("ok",success).param("e",error).param("id",id).update();}public void audit(String actor,String action,long id,String summary){jdbc.sql("insert into audit_log(action_type,target_type,target_id,summary,detail_json,correlation_id,created_at) values(:a,'EXTERNAL_SYSTEM',:id,:s,'{}',:c,:now)").param("a",action).param("id",id).param("s",summary+"；操作人="+actor).param("c","external-"+UUID.randomUUID()).param("now",OffsetDateTime.now()).update();}
 private ExternalSystemView view(ResultSet r,int n)throws SQLException{return new ExternalSystemView(r.getLong("id"),r.getString("system_code"),r.getString("system_name"),r.getString("system_type"),r.getString("description"),r.getString("icon"),r.getString("access_url"),r.getString("health_url"),r.getString("open_mode"),r.getBoolean("enabled"),r.getString("allowed_role"),r.getInt("sort_order"),r.getString("health_status"),r.getObject("last_checked_at",OffsetDateTime.class),r.getObject("last_success_at",OffsetDateTime.class),r.getString("last_error"));}
}
