package com.example.knowledgecollector.web.advanced;
import com.example.knowledgecollector.application.advanced.AdvancedCapabilityService;import com.example.knowledgecollector.web.api.ApiResponse;import com.example.knowledgecollector.web.api.CorrelationIdFilter;import jakarta.servlet.http.HttpServletRequest;import org.springframework.http.MediaType;import org.springframework.web.bind.annotation.*;import org.springframework.web.multipart.MultipartFile;import java.util.Map;
@RestController @RequestMapping("/api/v1/advanced") public class AdvancedCapabilityController {
 private final AdvancedCapabilityService service;public AdvancedCapabilityController(AdvancedCapabilityService service){this.service=service;}
 @GetMapping("/overview")public ApiResponse<?>overview(HttpServletRequest r){return ok(service.overview(),r);}@PostMapping(value="/documents",consumes=MediaType.MULTIPART_FORM_DATA_VALUE)public ApiResponse<?>document(@RequestPart("file")MultipartFile f,@RequestParam(defaultValue="AUTO")String method,@RequestParam(defaultValue="true")boolean createArticle,HttpServletRequest r)throws Exception{return ok(service.importDocument(f.getOriginalFilename(),f.getContentType()==null?MediaType.APPLICATION_OCTET_STREAM_VALUE:f.getContentType(),f.getBytes(),method,createArticle),r);}@PostMapping("/vectors/rebuild")public ApiResponse<?>rebuild(HttpServletRequest r){return ok(service.rebuildVectors(),r);}
 @PostMapping("/search")public ApiResponse<?>search(@RequestBody Map<String,Object>b,HttpServletRequest r){return ok(service.search(v(b,"query",""),v(b,"mode","HYBRID"),Boolean.parseBoolean(v(b,"rerank","true")),integer(b,"recall",10),integer(b,"limit",5),decimal(b,"reliabilityWeight",.2),decimal(b,"freshnessWeight",.2)),r);}@PostMapping("/academic/search")public ApiResponse<?>academic(@RequestBody Map<String,Object>b,HttpServletRequest r){return ok(service.academicSearch(v(b,"query",""),v(b,"doi",""),v(b,"author",""),v(b,"fromDate","")),r);}@PostMapping("/academic/import")public ApiResponse<?>paper(@RequestBody Map<String,Object>b,HttpServletRequest r){return ok(service.importPaper(b),r);}@PostMapping("/models/invoke")public ApiResponse<?>model(@RequestBody Map<String,Object>b,HttpServletRequest r){return ok(service.cloudModel(b),r);}
 @GetMapping("/monitor")public ApiResponse<?>monitor(HttpServletRequest r){return ok(service.monitor(),r);}@PostMapping("/notifications/test")public ApiResponse<?>notification(@RequestBody Map<String,Object>b,HttpServletRequest r){return ok(service.notify(b),r);}@PostMapping("/workflows/trigger")public ApiResponse<?>workflow(@RequestBody Map<String,Object>b,HttpServletRequest r){return ok(service.workflow(b),r);}@GetMapping("/executions")public ApiResponse<?>executions(@RequestParam(required=false)String stage,@RequestParam(defaultValue="50")int limit,HttpServletRequest r){return ok(service.executions(stage,limit),r);}@PostMapping("/executions/{id}/retry")public ApiResponse<?>retry(@PathVariable long id,HttpServletRequest r){return ok(service.retry(id),r);}@PostMapping("/settings")public ApiResponse<?>settings(@RequestBody Map<String,String>b,HttpServletRequest r){return ok(service.saveSettings(b),r);}
 private<T>ApiResponse<T>ok(T d,HttpServletRequest r){return ApiResponse.success(d,(String)r.getAttribute(CorrelationIdFilter.ATTRIBUTE_NAME));}private static String v(Map<String,Object>b,String k,String d){Object x=b.get(k);return x==null?d:String.valueOf(x);}private static int integer(Map<String,Object>b,String k,int d){try{return Integer.parseInt(v(b,k,""+d));}catch(Exception e){return d;}}private static double decimal(Map<String,Object>b,String k,double d){try{return Double.parseDouble(v(b,k,""+d));}catch(Exception e){return d;}}
}
