package com.example.knowledgecollector.infrastructure.security;
import com.example.knowledgecollector.application.exception.ResourceNotFoundException;import com.example.knowledgecollector.application.security.*;import org.springframework.jdbc.core.simple.JdbcClient;import org.springframework.stereotype.Repository;import java.sql.ResultSet;import java.sql.SQLException;import java.time.OffsetDateTime;import java.util.*;
@Repository public class JdbcUserGateway implements UserGateway {
 private final JdbcClient jdbc;public JdbcUserGateway(JdbcClient jdbc){this.jdbc=jdbc;}
 public List<UserView> list(String keyword,int offset,int limit){String k=keyword==null?"":keyword.trim().toLowerCase();return jdbc.sql("select * from app_user where :k='' or lower(username) like :like or lower(display_name) like :like order by id desc limit :limit offset :offset").param("k",k).param("like","%"+k+"%").param("limit",limit).param("offset",offset).query(this::view).list();}
 public long count(String keyword){String k=keyword==null?"":keyword.trim().toLowerCase();return jdbc.sql("select count(*) from app_user where :k='' or lower(username) like :like or lower(display_name) like :like").param("k",k).param("like","%"+k+"%").query(Long.class).single();}
 public Optional<UserCredentials> findCredentials(String username){return jdbc.sql("select id,username,display_name,password_hash,role_code,enabled from app_user where username=:u").param("u",username).query((r,n)->new UserCredentials(r.getLong(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getBoolean(6))).optional();}
 public UserView get(long id){return jdbc.sql("select * from app_user where id=:id").param("id",id).query(this::view).optional().orElseThrow(()->new ResourceNotFoundException("用户不存在："+id));}
 public long create(String username,String displayName,String hash,String role,boolean enabled){OffsetDateTime now=OffsetDateTime.now();jdbc.sql("insert into app_user(username,display_name,password_hash,role_code,enabled,password_changed_at,created_at,updated_at) values(:u,:d,:p,:r,:e,:now,:now,:now)").param("u",username).param("d",displayName).param("p",hash).param("r",role).param("e",enabled).param("now",now).update();return jdbc.sql("select id from app_user where username=:u").param("u",username).query(Long.class).single();}
 public UserView update(long id,String displayName,String role,boolean enabled){int changed=jdbc.sql("update app_user set display_name=:d,role_code=:r,enabled=:e,updated_at=:now where id=:id").param("d",displayName).param("r",role).param("e",enabled).param("now",OffsetDateTime.now()).param("id",id).update();if(changed==0)throw new ResourceNotFoundException("用户不存在："+id);return get(id);}
 public void updatePassword(long id,String hash){if(jdbc.sql("update app_user set password_hash=:p,password_changed_at=:now,updated_at=:now where id=:id").param("p",hash).param("now",OffsetDateTime.now()).param("id",id).update()==0)throw new ResourceNotFoundException("用户不存在："+id);}
 public void recordLogin(long id){jdbc.sql("update app_user set last_login_at=:now,updated_at=:now where id=:id").param("now",OffsetDateTime.now()).param("id",id).update();}
 public void audit(String actor,String action,String targetType,String targetId,String summary,String detail){jdbc.sql("insert into audit_log(action_type,target_type,target_id,summary,detail_json,correlation_id,created_at) values(:a,:t,:id,:s,:d,:c,:now)").param("a",action).param("t",targetType).param("id",parse(targetId)).param("s",summary+"；操作人="+actor).param("d",detail).param("c","security-"+UUID.randomUUID()).param("now",OffsetDateTime.now()).update();}
 private UserView view(ResultSet r,int n)throws SQLException{return new UserView(r.getLong("id"),r.getString("username"),r.getString("display_name"),r.getString("role_code"),r.getBoolean("enabled"),r.getObject("last_login_at",OffsetDateTime.class),r.getObject("password_changed_at",OffsetDateTime.class),r.getObject("created_at",OffsetDateTime.class),r.getObject("updated_at",OffsetDateTime.class));}private static Long parse(String s){try{return Long.valueOf(s);}catch(Exception e){return null;}}
}
