package com.example.knowledgecollector.application.externalsystem;
import com.example.knowledgecollector.application.exception.BusinessRuleException;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.net.URI;import java.net.http.*;import java.time.*;import java.util.List;import java.util.Locale;
@Service public class ExternalSystemService {
 private final ExternalSystemGateway gateway;private final HttpClient http=HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(5)).build();public ExternalSystemService(ExternalSystemGateway gateway){this.gateway=gateway;}public List<ExternalSystemView> list(){return gateway.list();}public ExternalSystemView get(long id){return gateway.get(id);}
 @Transactional public ExternalSystemView create(String actor,ExternalSystemCommand c){validate(c);long id=gateway.create(normalize(c));gateway.audit(actor,"EXTERNAL_SYSTEM_CREATE",id,"创建第三方系统 "+c.name());return gateway.get(id);}@Transactional public ExternalSystemView update(String actor,long id,ExternalSystemCommand c){validate(c);var v=gateway.update(id,normalize(c));gateway.audit(actor,"EXTERNAL_SYSTEM_UPDATE",id,"更新第三方系统 "+v.name());return v;}@Transactional public ExternalSystemView enable(String actor,long id,boolean enabled){var v=gateway.setEnabled(id,enabled);gateway.audit(actor,"EXTERNAL_SYSTEM_STATUS",id,(enabled?"启用":"停用")+"第三方系统 "+v.name());return v;}
 @Transactional public ExternalSystemView test(String actor,long id){var v=gateway.get(id);OffsetDateTime now=OffsetDateTime.now();if(!v.enabled()){gateway.updateHealth(id,"DISABLED",now,null,"服务已停用");return gateway.get(id);}String target=blank(v.healthUrl())?v.accessUrl():v.healthUrl();if(blank(target)){gateway.updateHealth(id,"UNCONFIGURED",now,null,"未配置访问地址");return gateway.get(id);}try{URI uri=safeUri(target);var response=http.send(HttpRequest.newBuilder(uri).timeout(Duration.ofSeconds(8)).GET().build(),HttpResponse.BodyHandlers.discarding());boolean ok=response.statusCode()>=200&&response.statusCode()<400;gateway.updateHealth(id,ok?"HEALTHY":"UNHEALTHY",now,ok?now:null,ok?null:"HTTP "+response.statusCode());gateway.audit(actor,"EXTERNAL_SYSTEM_TEST",id,"检测第三方系统 "+v.name()+"：HTTP "+response.statusCode());}catch(Exception e){gateway.updateHealth(id,"UNHEALTHY",now,null,safe(e));gateway.audit(actor,"EXTERNAL_SYSTEM_TEST",id,"检测第三方系统失败 "+v.name());}return gateway.get(id);}
 public String openUrl(long id){var v=gateway.get(id);if(!v.enabled())throw new BusinessRuleException("EXTERNAL-SYSTEM-DISABLED","服务已停用");if(blank(v.accessUrl()))throw new BusinessRuleException("EXTERNAL-SYSTEM-UNCONFIGURED","服务未配置访问地址");return safeUri(v.accessUrl()).toString();}
 private static void validate(ExternalSystemCommand c){if(c==null||blank(c.code())||blank(c.name())||blank(c.type()))throw new BusinessRuleException("EXTERNAL-SYSTEM-FIELD-EMPTY","服务代码、名称和类型不能为空");if(!blank(c.accessUrl()))safeUri(c.accessUrl());if(!blank(c.healthUrl()))safeUri(c.healthUrl());}private static ExternalSystemCommand normalize(ExternalSystemCommand c){return new ExternalSystemCommand(c.code().trim().toUpperCase(Locale.ROOT),c.name().trim(),c.type().trim().toUpperCase(Locale.ROOT),c.description(),blank(c.icon())?"LINK":c.icon().trim(),c.accessUrl(),c.healthUrl(),"NEW_TAB".equalsIgnoreCase(c.openMode())?"NEW_TAB":"CURRENT",c.enabled(),"USER".equalsIgnoreCase(c.allowedRole())?"USER":"ADMIN",Math.max(0,c.sortOrder()));}private static URI safeUri(String s){try{URI u=URI.create(s.trim());String q=u.getRawQuery()==null?"":u.getRawQuery().toLowerCase(Locale.ROOT);if((!"http".equalsIgnoreCase(u.getScheme())&&!"https".equalsIgnoreCase(u.getScheme()))||u.getHost()==null||u.getUserInfo()!=null||q.matches(".*(^|[&])(token|password|passwd|secret|api[_-]?key)=.*"))throw new Exception();return u;}catch(Exception e){throw new BusinessRuleException("EXTERNAL-SYSTEM-URL-INVALID","地址必须是且不得携带凭证的 HTTP/HTTPS URL");}}private static boolean blank(String s){return s==null||s.isBlank();}private static String safe(Exception e){String m=e.getMessage();return m==null?e.getClass().getSimpleName():m.substring(0,Math.min(1000,m.length()));}
}
