package com.example.knowledgecollector;

import com.fasterxml.jackson.databind.JsonNode;import com.github.tomakehurst.wiremock.WireMockServer;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.boot.test.web.client.TestRestTemplate;import org.springframework.boot.test.web.server.LocalServerPort;import org.springframework.core.io.ByteArrayResource;import org.springframework.http.*;import org.springframework.test.context.ActiveProfiles;import org.springframework.test.context.DynamicPropertyRegistry;import org.springframework.test.context.DynamicPropertySource;import org.springframework.util.LinkedMultiValueMap;import java.nio.charset.StandardCharsets;import java.util.Map;import static com.github.tomakehurst.wiremock.client.WireMock.*;import static com.github.tomakehurst.wiremock.core.WireMockConfiguration.options;import static org.assertj.core.api.Assertions.assertThat;

@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT) @ActiveProfiles({"test","local"})
class Stage30To38AdvancedIntegrationTest {
 static final WireMockServer REMOTE=new WireMockServer(options().dynamicPort());
 static{REMOTE.start();REMOTE.stubFor(any(anyUrl()).atPriority(10).willReturn(okJson("{}")));REMOTE.stubFor(put(urlEqualTo("/tika")).willReturn(ok("Stage 30 document content that is long enough to create a verifiable library article.")));REMOTE.stubFor(delete(urlEqualTo("/collections/knowledge")).willReturn(okJson("{}")));REMOTE.stubFor(put(urlPathMatching("/collections/knowledge.*")).willReturn(okJson("{\"result\":true}")));REMOTE.stubFor(com.github.tomakehurst.wiremock.client.WireMock.post(urlEqualTo("/collections/knowledge/points/search")).willReturn(okJson("{\"result\":[]}")));REMOTE.stubFor(com.github.tomakehurst.wiremock.client.WireMock.get(urlPathMatching("/works.*")).willReturn(okJson("{\"message\":{\"items\":[{\"title\":[\"Knowledge management verification paper\"],\"DOI\":\"10.1000/stage33\"}]}}")));REMOTE.stubFor(com.github.tomakehurst.wiremock.client.WireMock.post(urlEqualTo("/chat")).willReturn(okJson("{\"choices\":[{\"message\":{\"content\":\"Stage 34 model response\"}}],\"usage\":{\"total_tokens\":42}}")));REMOTE.stubFor(com.github.tomakehurst.wiremock.client.WireMock.post(urlEqualTo("/knowledge-alerts")).willReturn(okJson("{\"id\":\"stage37\"}")));REMOTE.stubFor(com.github.tomakehurst.wiremock.client.WireMock.post(urlEqualTo("/webhook/knowledge-collector")).willReturn(okJson("{\"accepted\":true}")));}
 @DynamicPropertySource static void props(DynamicPropertyRegistry r){r.add("spring.datasource.url",()->"jdbc:h2:mem:stage30-38;DB_CLOSE_DELAY=-1");r.add("knowledge-collector.advanced.tika-url",REMOTE::baseUrl);r.add("knowledge-collector.advanced.qdrant-url",REMOTE::baseUrl);r.add("knowledge-collector.advanced.crossref-url",REMOTE::baseUrl);r.add("knowledge-collector.advanced.ntfy-url",REMOTE::baseUrl);r.add("knowledge-collector.advanced.n8n-url",REMOTE::baseUrl);r.add("knowledge-collector.advanced.grafana-url",REMOTE::baseUrl);r.add("knowledge-collector.advanced.langfuse-url",REMOTE::baseUrl);}
 @Autowired TestRestTemplate http;@LocalServerPort int port;@AfterAll static void stop(){REMOTE.stop();}
 @Test void stage30To38BusinessLoopsAreExecutable(){
  var multipart=new LinkedMultiValueMap<String,Object>();multipart.add("method","AUTO");multipart.add("createArticle","true");multipart.add("file",new ByteArrayResource("verification document".getBytes(StandardCharsets.UTF_8)){@Override public String getFilename(){return "stage30.txt";}});HttpHeaders mh=new HttpHeaders();mh.setContentType(MediaType.MULTIPART_FORM_DATA);JsonNode doc=exchange("/api/v1/advanced/documents",HttpMethod.POST,new HttpEntity<>(multipart,mh)).path("data");assertThat(doc.path("status").asText()).isEqualTo("SUCCESS");assertThat(doc.path("articleId").asLong()).isPositive();
  assertSuccess(post("/api/v1/advanced/vectors/rebuild",Map.of()));JsonNode search=post("/api/v1/advanced/search",Map.of("query","Stage document","mode","HYBRID","rerank",true,"recall",10,"limit",5));assertSuccess(search);assertThat(search.path("data").path("keyword").size()).isPositive();
  JsonNode papers=post("/api/v1/advanced/academic/search",Map.of("query","knowledge management","fromDate","2024-01-01"));assertSuccess(papers);assertThat(papers.path("data").path("items").size()).isEqualTo(1);assertSuccess(post("/api/v1/advanced/academic/import",Map.of("title","Stage 33 paper","DOI","10.1000/stage33","abstract","Verified abstract")));
  JsonNode model=post("/api/v1/advanced/models/invoke",Map.of("endpoint",REMOTE.baseUrl()+"/chat","apiKey","must-not-persist","model","test-model","content","safe preview"));assertSuccess(model);assertThat(model.path("data").path("output").asText()).isEqualTo("Stage 34 model response");
  assertSuccess(get("/api/v1/advanced/monitor"));assertSuccess(post("/api/v1/advanced/notifications/test",Map.of("url",REMOTE.baseUrl(),"topic","knowledge-alerts","message","Stage 37")));assertSuccess(post("/api/v1/advanced/workflows/trigger",Map.of("webhook",REMOTE.baseUrl()+"/webhook/knowledge-collector","contentType","ARTICLE","businessId",doc.path("articleId").asLong())));
  JsonNode logs=get("/api/v1/advanced/executions?limit=100");assertThat(logs.path("data").size()).isGreaterThanOrEqualTo(8);assertThat(logs.toString()).doesNotContain("must-not-persist");String page=http.getForObject(url("/advanced"),String.class);assertThat(page).contains("Stage 30","Stage 38","增强能力工作台");
 }
 private void assertSuccess(JsonNode n){assertThat(n.path("success").asBoolean()).isTrue();assertThat(n.path("data").path("status").asText()).isEqualTo("SUCCESS");}private JsonNode get(String p){return http.getForObject(url(p),JsonNode.class);}private JsonNode post(String p,Object b){HttpHeaders h=new HttpHeaders();h.setContentType(MediaType.APPLICATION_JSON);return exchange(p,HttpMethod.POST,new HttpEntity<>(b,h));}private JsonNode exchange(String p,HttpMethod m,HttpEntity<?> e){var r=http.exchange(url(p),m,e,JsonNode.class);assertThat(r.getStatusCode().is2xxSuccessful()).isTrue();return r.getBody();}private String url(String p){return "http://127.0.0.1:"+port+p;}
}
