CREATE TABLE ai_conversation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    provider VARCHAR(64) NOT NULL,
    model VARCHAR(128),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE ai_chat_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL,
    role VARCHAR(16) NOT NULL,
    content CLOB NOT NULL,
    model VARCHAR(128),
    prompt_tokens INTEGER,
    response_tokens INTEGER,
    duration_millis BIGINT,
    saved_article_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_ai_message_conversation FOREIGN KEY(conversation_id)
        REFERENCES ai_conversation(id) ON DELETE CASCADE,
    CONSTRAINT ck_ai_message_role CHECK(role IN ('USER','ASSISTANT'))
);
CREATE INDEX idx_ai_conversation_updated ON ai_conversation(updated_at);
CREATE INDEX idx_ai_message_conversation ON ai_chat_message(conversation_id,id);

ALTER TABLE article ADD COLUMN content_origin VARCHAR(32) NOT NULL DEFAULT 'COLLECTED';
ALTER TABLE article ADD COLUMN ai_conversation_id BIGINT;
ALTER TABLE article ADD COLUMN ai_message_id BIGINT;
ALTER TABLE article ADD CONSTRAINT fk_article_ai_conversation
    FOREIGN KEY(ai_conversation_id) REFERENCES ai_conversation(id);
ALTER TABLE article ADD CONSTRAINT fk_article_ai_message
    FOREIGN KEY(ai_message_id) REFERENCES ai_chat_message(id);
CREATE INDEX idx_article_content_origin ON article(content_origin,review_status);

INSERT INTO crawl_source(
    source_code,source_name,source_type,home_url,feed_url,language,charset,user_agent,
    timeout_seconds,max_retries,request_interval_millis,obey_robots,fetch_full_content,
    summary_only,save_snapshot,enabled,notes,created_at,updated_at
)
SELECT 'SYSTEM_AI','AI 生成内容','MANUAL_URL','http://127.0.0.1/ai-chat',
       'http://127.0.0.1/ai-chat','zh-CN','UTF-8','KnowledgeCollector-AI',
       15,0,0,FALSE,FALSE,FALSE,FALSE,FALSE,
       '系统内置来源：保存自 AI 对话，必须人工审核。',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM crawl_source WHERE source_code='SYSTEM_AI');
