ALTER TABLE crawl_source ADD COLUMN health_status VARCHAR(16) NOT NULL DEFAULT 'UNKNOWN';
ALTER TABLE crawl_source ADD COLUMN last_health_checked_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE crawl_source ADD COLUMN last_health_message VARCHAR(1000);
CREATE INDEX idx_source_health ON crawl_source(health_status, last_health_checked_at);

CREATE INDEX idx_task_created_status ON crawl_task(created_at, status);

CREATE TABLE archive_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_name VARCHAR(128) NOT NULL,
    keyword VARCHAR(200),
    topic_id BIGINT,
    source_id BIGINT,
    min_quality INTEGER,
    sort_order INTEGER NOT NULL DEFAULT 0,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_archive_rule_quality CHECK (min_quality IS NULL OR min_quality BETWEEN 0 AND 100),
    CONSTRAINT fk_archive_rule_topic FOREIGN KEY(topic_id) REFERENCES topic(id) ON DELETE SET NULL,
    CONSTRAINT fk_archive_rule_source FOREIGN KEY(source_id) REFERENCES crawl_source(id) ON DELETE SET NULL
);

INSERT INTO archive_rule(rule_name,min_quality,sort_order,enabled,created_at,updated_at)
VALUES('高质量资料',80,10,TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
