CREATE TABLE knowledge_card (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id BIGINT,
    topic_id BIGINT,
    title VARCHAR(240) NOT NULL,
    content CLOB NOT NULL,
    card_type VARCHAR(32) NOT NULL,
    source_quote CLOB,
    source_location VARCHAR(500),
    author VARCHAR(200),
    source_name VARCHAR(240),
    published_at TIMESTAMP WITH TIME ZONE,
    tags VARCHAR(1000),
    user_note CLOB,
    confidence INTEGER NOT NULL DEFAULT 50,
    verification_status VARCHAR(32) NOT NULL DEFAULT 'UNVERIFIED',
    ai_suggested BOOLEAN NOT NULL DEFAULT FALSE,
    confirmed BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_card_article FOREIGN KEY(article_id) REFERENCES article(id) ON DELETE SET NULL,
    CONSTRAINT fk_card_topic FOREIGN KEY(topic_id) REFERENCES topic(id) ON DELETE SET NULL,
    CONSTRAINT ck_card_confidence CHECK(confidence BETWEEN 0 AND 100)
);
CREATE INDEX idx_card_article ON knowledge_card(article_id, created_at);
CREATE INDEX idx_card_type ON knowledge_card(card_type, verification_status);

CREATE TABLE knowledge_claim (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    statement CLOB NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING_VERIFICATION',
    assumptions CLOB,
    scope_note CLOB,
    limitations CLOB,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE claim_evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id BIGINT NOT NULL,
    article_id BIGINT,
    card_id BIGINT,
    evidence_type VARCHAR(24) NOT NULL,
    excerpt CLOB NOT NULL,
    citation VARCHAR(1000),
    strength INTEGER NOT NULL DEFAULT 50,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_evidence_claim FOREIGN KEY(claim_id) REFERENCES knowledge_claim(id) ON DELETE CASCADE,
    CONSTRAINT fk_evidence_article FOREIGN KEY(article_id) REFERENCES article(id) ON DELETE SET NULL,
    CONSTRAINT fk_evidence_card FOREIGN KEY(card_id) REFERENCES knowledge_card(id) ON DELETE SET NULL,
    CONSTRAINT ck_evidence_strength CHECK(strength BETWEEN 0 AND 100)
);
CREATE INDEX idx_evidence_claim ON claim_evidence(claim_id, evidence_type);

CREATE TABLE knowledge_entity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR(32) NOT NULL,
    canonical_name VARCHAR(240) NOT NULL,
    description CLOB,
    aliases VARCHAR(2000),
    merged_into_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_entity_name UNIQUE(entity_type, canonical_name),
    CONSTRAINT fk_entity_merged FOREIGN KEY(merged_into_id) REFERENCES knowledge_entity(id)
);

CREATE TABLE entity_reference (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id BIGINT NOT NULL,
    article_id BIGINT,
    card_id BIGINT,
    claim_id BIGINT,
    relation_type VARCHAR(32) NOT NULL DEFAULT 'MENTIONED_IN',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_reference_entity FOREIGN KEY(entity_id) REFERENCES knowledge_entity(id) ON DELETE CASCADE,
    CONSTRAINT fk_reference_article FOREIGN KEY(article_id) REFERENCES article(id) ON DELETE CASCADE,
    CONSTRAINT fk_reference_card FOREIGN KEY(card_id) REFERENCES knowledge_card(id) ON DELETE CASCADE,
    CONSTRAINT fk_reference_claim FOREIGN KEY(claim_id) REFERENCES knowledge_claim(id) ON DELETE CASCADE
);

CREATE TABLE knowledge_relation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_card_id BIGINT NOT NULL,
    to_card_id BIGINT NOT NULL,
    relation_type VARCHAR(24) NOT NULL,
    note VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_relation_from FOREIGN KEY(from_card_id) REFERENCES knowledge_card(id) ON DELETE CASCADE,
    CONSTRAINT fk_relation_to FOREIGN KEY(to_card_id) REFERENCES knowledge_card(id) ON DELETE CASCADE,
    CONSTRAINT uq_card_relation UNIQUE(from_card_id, to_card_id, relation_type)
);

CREATE TABLE knowledge_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(240) NOT NULL,
    summary CLOB,
    event_date DATE,
    cluster_key VARCHAR(200),
    status VARCHAR(24) NOT NULL DEFAULT 'TRACKING',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE event_article (
    event_id BIGINT NOT NULL,
    article_id BIGINT NOT NULL,
    source_role VARCHAR(24) NOT NULL DEFAULT 'MEDIA',
    confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY(event_id, article_id),
    CONSTRAINT fk_event_article_event FOREIGN KEY(event_id) REFERENCES knowledge_event(id) ON DELETE CASCADE,
    CONSTRAINT fk_event_article_article FOREIGN KEY(article_id) REFERENCES article(id) ON DELETE CASCADE
);

CREATE TABLE knowledge_topic_page (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id BIGINT,
    name VARCHAR(240) NOT NULL,
    introduction CLOB,
    knowledge_summary CLOB,
    reading_order CLOB,
    unresolved_questions CLOB,
    user_summary CLOB,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_knowledge_topic FOREIGN KEY(topic_id) REFERENCES topic(id) ON DELETE SET NULL
);

CREATE TABLE research_project (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(240) NOT NULL,
    objective CLOB NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
    core_questions CLOB,
    hypotheses CLOB,
    conclusions CLOB,
    research_log CLOB,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE research_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    article_id BIGINT,
    card_id BIGINT,
    claim_id BIGINT,
    usage_type VARCHAR(32) NOT NULL,
    note CLOB,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_research_item_project FOREIGN KEY(project_id) REFERENCES research_project(id) ON DELETE CASCADE,
    CONSTRAINT fk_research_item_article FOREIGN KEY(article_id) REFERENCES article(id) ON DELETE CASCADE,
    CONSTRAINT fk_research_item_card FOREIGN KEY(card_id) REFERENCES knowledge_card(id) ON DELETE CASCADE,
    CONSTRAINT fk_research_item_claim FOREIGN KEY(claim_id) REFERENCES knowledge_claim(id) ON DELETE CASCADE
);

CREATE TABLE knowledge_synthesis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT,
    topic_page_id BIGINT,
    title VARCHAR(240) NOT NULL,
    synthesis_type VARCHAR(32) NOT NULL,
    content CLOB NOT NULL,
    source_references CLOB NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'DRAFT',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_synthesis_project FOREIGN KEY(project_id) REFERENCES research_project(id) ON DELETE SET NULL,
    CONSTRAINT fk_synthesis_topic FOREIGN KEY(topic_page_id) REFERENCES knowledge_topic_page(id) ON DELETE SET NULL
);

CREATE TABLE writing_draft (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT,
    title VARCHAR(240) NOT NULL,
    outline CLOB,
    content CLOB,
    source_references CLOB NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'DRAFT',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_draft_project FOREIGN KEY(project_id) REFERENCES research_project(id) ON DELETE SET NULL
);

CREATE TABLE knowledge_gap (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT,
    topic_page_id BIGINT,
    claim_id BIGINT,
    gap_type VARCHAR(32) NOT NULL,
    description CLOB NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'OPEN',
    due_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_gap_project FOREIGN KEY(project_id) REFERENCES research_project(id) ON DELETE CASCADE,
    CONSTRAINT fk_gap_topic FOREIGN KEY(topic_page_id) REFERENCES knowledge_topic_page(id) ON DELETE CASCADE,
    CONSTRAINT fk_gap_claim FOREIGN KEY(claim_id) REFERENCES knowledge_claim(id) ON DELETE CASCADE
);

CREATE TABLE knowledge_review (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_id BIGINT NOT NULL,
    review_type VARCHAR(24) NOT NULL DEFAULT 'SPACED',
    due_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_reviewed_at TIMESTAMP WITH TIME ZONE,
    review_count INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_review_card FOREIGN KEY(card_id) REFERENCES knowledge_card(id) ON DELETE CASCADE
);
CREATE INDEX idx_review_due ON knowledge_review(active, due_at);
