CREATE TABLE third_party_service (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id VARCHAR(64) NOT NULL UNIQUE,
    service_name VARCHAR(128) NOT NULL,
    service_type VARCHAR(32) NOT NULL,
    implementation_name VARCHAR(300) NOT NULL,
    endpoint VARCHAR(2048) NOT NULL,
    model VARCHAR(200),
    authentication_type VARCHAR(32) NOT NULL DEFAULT 'NONE',
    credential CLOB,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    default_provider BOOLEAN NOT NULL DEFAULT FALSE,
    fallback_provider BOOLEAN NOT NULL DEFAULT FALSE,
    user_configured BOOLEAN NOT NULL DEFAULT FALSE,
    health_status VARCHAR(24) NOT NULL DEFAULT 'UNKNOWN',
    last_checked_at TIMESTAMP WITH TIME ZONE,
    last_success_at TIMESTAMP WITH TIME ZONE,
    last_error CLOB,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE SEQUENCE third_party_call_log_seq START WITH 1 INCREMENT BY 1;
CREATE TABLE third_party_call_log (
    id BIGINT DEFAULT NEXT VALUE FOR third_party_call_log_seq PRIMARY KEY,
    provider_id VARCHAR(64) NOT NULL,
    operation VARCHAR(80) NOT NULL,
    business_scene VARCHAR(120) NOT NULL,
    status VARCHAR(24) NOT NULL,
    request_summary CLOB,
    result_summary CLOB,
    error_message CLOB,
    retry_of_id BIGINT,
    duration_millis BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    finished_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_call_retry FOREIGN KEY(retry_of_id) REFERENCES third_party_call_log(id)
);
CREATE INDEX idx_third_party_call_provider ON third_party_call_log(provider_id, created_at);

CREATE TABLE source_discovery_candidate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id VARCHAR(64) NOT NULL,
    topic VARCHAR(128) NOT NULL,
    name VARCHAR(300) NOT NULL,
    website_url VARCHAR(2048) NOT NULL,
    collection_url VARCHAR(2048) NOT NULL,
    source_type VARCHAR(32) NOT NULL,
    language VARCHAR(16) NOT NULL,
    reliability_score INTEGER NOT NULL,
    validation_status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
    recommendation_reason CLOB,
    validation_message CLOB,
    imported_source_id BIGINT,
    ignored BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    validated_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_candidate_score CHECK(reliability_score BETWEEN 0 AND 100),
    CONSTRAINT fk_candidate_source FOREIGN KEY(imported_source_id) REFERENCES crawl_source(id) ON DELETE SET NULL
);
CREATE INDEX idx_discovery_candidate_status ON source_discovery_candidate(ignored, validation_status, created_at);

INSERT INTO third_party_service(provider_id,service_name,service_type,implementation_name,endpoint,model,
 authentication_type,enabled,default_provider,fallback_provider,health_status,created_at,updated_at)
VALUES('ollama','Ollama 本地大模型','AI','com.example.knowledgecollector.provider.intelligence.OllamaContentIntelligenceProvider',
 'http://127.0.0.1:11434','deepseek-r1:14b','NONE',TRUE,TRUE,FALSE,'UNKNOWN',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

INSERT INTO third_party_service(provider_id,service_name,service_type,implementation_name,endpoint,model,
 authentication_type,enabled,default_provider,fallback_provider,health_status,created_at,updated_at)
VALUES('searxng','SearXNG 元搜索','SEARCH','com.example.knowledgecollector.provider.search.SearxngSourceDiscoveryProvider',
 'http://127.0.0.1:8088',NULL,'NONE',FALSE,TRUE,FALSE,'UNKNOWN',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
