CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    display_name VARCHAR(120) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    role_code VARCHAR(32) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    password_changed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_login_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_app_user_username UNIQUE(username),
    CONSTRAINT ck_app_user_role CHECK(role_code IN ('USER','ADMIN'))
);
CREATE INDEX idx_app_user_status ON app_user(enabled,role_code);

CREATE TABLE external_system (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    system_code VARCHAR(64) NOT NULL,
    system_name VARCHAR(120) NOT NULL,
    system_type VARCHAR(64) NOT NULL,
    description VARCHAR(1000),
    icon VARCHAR(32) NOT NULL DEFAULT 'LINK',
    access_url VARCHAR(2048),
    health_url VARCHAR(2048),
    open_mode VARCHAR(16) NOT NULL DEFAULT 'CURRENT',
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    allowed_role VARCHAR(32) NOT NULL DEFAULT 'ADMIN',
    sort_order INTEGER NOT NULL DEFAULT 100,
    health_status VARCHAR(32) NOT NULL DEFAULT 'UNCHECKED',
    last_checked_at TIMESTAMP WITH TIME ZONE,
    last_success_at TIMESTAMP WITH TIME ZONE,
    last_error VARCHAR(2000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_external_system_code UNIQUE(system_code),
    CONSTRAINT ck_external_open_mode CHECK(open_mode IN ('CURRENT','NEW_TAB')),
    CONSTRAINT ck_external_role CHECK(allowed_role IN ('USER','ADMIN')),
    CONSTRAINT ck_external_health_status CHECK(health_status IN ('UNCHECKED','HEALTHY','UNHEALTHY','UNCONFIGURED','DISABLED','CHECKING'))
);

INSERT INTO external_system(system_code,system_name,system_type,description,icon,access_url,health_url,open_mode,enabled,sort_order,created_at,updated_at) VALUES
('MINIO','MinIO','OBJECT_STORAGE','原始证据、附件与快照对象存储','MI','http://127.0.0.1:9001','http://minio:9000/minio/health/live','NEW_TAB',TRUE,10,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('GRAFANA','Grafana','MONITORING','系统指标与趋势仪表盘','GF','http://127.0.0.1:3000','http://grafana:3000/api/health','NEW_TAB',TRUE,20,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('OLLAMA','Ollama','AI_MODEL','本地大模型推理服务','OL','http://127.0.0.1:11434','http://ollama:11434/api/tags','CURRENT',TRUE,30,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('LANGFUSE','Langfuse','AI_OBSERVABILITY','AI 调用链路与 Prompt 可观测性','LF',NULL,NULL,'NEW_TAB',FALSE,40,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('SEARXNG','SearXNG','SEARCH','主题采集源搜索发现服务','SX','http://127.0.0.1:8088','http://searxng:8080/healthz','CURRENT',TRUE,50,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('FIRECRAWL','Firecrawl','EXTRACTION','网页正文提取服务','FC',NULL,NULL,'CURRENT',FALSE,60,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('QDRANT','Qdrant','VECTOR','向量索引与语义检索服务','QD','http://127.0.0.1:6333/dashboard','http://qdrant:6333/healthz','NEW_TAB',TRUE,70,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('PROMETHEUS','Prometheus','MONITORING','指标采集与查询服务','PM','http://127.0.0.1:9090','http://prometheus:9090/-/ready','NEW_TAB',TRUE,80,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('NTFY','ntfy','NOTIFICATION','手机与桌面消息通知服务','NT','http://127.0.0.1:8085','http://ntfy:80/v1/health','NEW_TAB',TRUE,90,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('N8N','n8n','WORKFLOW','外部自动化工作流服务','N8','http://127.0.0.1:5678','http://n8n:5678/healthz','NEW_TAB',TRUE,100,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
