create table system_setting (
    id bigint generated by default as identity primary key,
    setting_key varchar(128) not null,
    setting_value clob,
    value_type varchar(32) not null,
    description varchar(512),
    updated_at timestamp with time zone not null,
    constraint uk_system_setting_key unique (setting_key)
);

create table audit_log (
    id bigint generated by default as identity primary key,
    action_type varchar(64) not null,
    target_type varchar(64),
    target_id bigint,
    summary varchar(512) not null,
    detail_json clob,
    correlation_id varchar(64),
    created_at timestamp with time zone not null
);

create index idx_audit_log_created_at on audit_log (created_at);
create index idx_audit_log_target on audit_log (target_type, target_id);

insert into system_setting
    (setting_key, setting_value, value_type, description, updated_at)
values
    ('system.startup-count', '0', 'LONG', 'Number of successfully initialized application contexts', current_timestamp);

insert into system_setting
    (setting_key, setting_value, value_type, description, updated_at)
values
    ('system.last-started-at', '1970-01-01T00:00:00Z', 'OFFSET_DATE_TIME', 'Most recent successful application initialization time', current_timestamp);
