CREATE TABLE topic (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_code VARCHAR(64) NOT NULL,
    topic_name VARCHAR(128) NOT NULL,
    description VARCHAR(1000),
    keywords CLOB NOT NULL DEFAULT '',
    excluded_keywords CLOB NOT NULL DEFAULT '',
    color VARCHAR(16) NOT NULL DEFAULT '#2563EB',
    icon VARCHAR(64),
    language VARCHAR(16) NOT NULL DEFAULT 'zh-CN',
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    lock_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_topic_code UNIQUE (topic_code),
    CONSTRAINT uk_topic_name UNIQUE (topic_name)
);

CREATE INDEX idx_topic_enabled_sort ON topic(enabled, sort_order);

CREATE TABLE crawl_source (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_code VARCHAR(64) NOT NULL,
    source_name VARCHAR(128) NOT NULL,
    source_type VARCHAR(32) NOT NULL,
    home_url VARCHAR(2048),
    feed_url VARCHAR(2048),
    language VARCHAR(16) NOT NULL DEFAULT 'zh-CN',
    charset VARCHAR(32) NOT NULL DEFAULT 'UTF-8',
    user_agent VARCHAR(256) NOT NULL,
    timeout_seconds INTEGER NOT NULL DEFAULT 15,
    max_retries INTEGER NOT NULL DEFAULT 2,
    request_interval_millis BIGINT NOT NULL DEFAULT 2000,
    obey_robots BOOLEAN NOT NULL DEFAULT TRUE,
    fetch_full_content BOOLEAN NOT NULL DEFAULT TRUE,
    summary_only BOOLEAN NOT NULL DEFAULT FALSE,
    save_snapshot BOOLEAN NOT NULL DEFAULT FALSE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    last_success_at TIMESTAMP WITH TIME ZONE,
    last_failure_at TIMESTAMP WITH TIME ZONE,
    consecutive_failures INTEGER NOT NULL DEFAULT 0,
    notes VARCHAR(2000),
    lock_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_source_code UNIQUE (source_code),
    CONSTRAINT ck_source_timeout CHECK (timeout_seconds BETWEEN 1 AND 120),
    CONSTRAINT ck_source_retries CHECK (max_retries BETWEEN 0 AND 10),
    CONSTRAINT ck_source_interval CHECK (request_interval_millis BETWEEN 0 AND 3600000)
);

CREATE INDEX idx_source_type_enabled ON crawl_source(source_type, enabled);
CREATE INDEX idx_source_last_success ON crawl_source(last_success_at);
CREATE INDEX idx_source_failures ON crawl_source(consecutive_failures);

CREATE TABLE topic_source_rel (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id BIGINT NOT NULL,
    source_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_topic_source UNIQUE (topic_id, source_id),
    CONSTRAINT fk_topic_source_topic FOREIGN KEY (topic_id) REFERENCES topic(id),
    CONSTRAINT fk_topic_source_source FOREIGN KEY (source_id) REFERENCES crawl_source(id) ON DELETE CASCADE
);

CREATE INDEX idx_topic_source_source ON topic_source_rel(source_id);
