CREATE TABLE crawl_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_no VARCHAR(64) NOT NULL,
    retry_of_task_id BIGINT,
    trigger_type VARCHAR(32) NOT NULL,
    source_id BIGINT NOT NULL,
    active_source_id BIGINT,
    status VARCHAR(32) NOT NULL,
    discovered_count INTEGER NOT NULL DEFAULT 0,
    created_count INTEGER NOT NULL DEFAULT 0,
    duplicate_count INTEGER NOT NULL DEFAULT 0,
    updated_count INTEGER NOT NULL DEFAULT 0,
    skipped_count INTEGER NOT NULL DEFAULT 0,
    failed_count INTEGER NOT NULL DEFAULT 0,
    manually_triggered BOOLEAN NOT NULL DEFAULT TRUE,
    started_at TIMESTAMP WITH TIME ZONE,
    finished_at TIMESTAMP WITH TIME ZONE,
    duration_millis BIGINT,
    error_code VARCHAR(64),
    error_message VARCHAR(1000),
    lock_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_task_no UNIQUE(task_no),
    CONSTRAINT uk_task_active_source UNIQUE(active_source_id),
    CONSTRAINT fk_task_source FOREIGN KEY(source_id) REFERENCES crawl_source(id)
);
CREATE INDEX idx_task_status ON crawl_task(status);
CREATE INDEX idx_task_source_created ON crawl_task(source_id, created_at);

CREATE TABLE article (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id BIGINT NOT NULL,
    title VARCHAR(500) NOT NULL,
    author VARCHAR(256),
    summary CLOB,
    original_url VARCHAR(2048) NOT NULL,
    normalized_url VARCHAR(2048) NOT NULL,
    url_hash CHAR(64) NOT NULL,
    language VARCHAR(16) NOT NULL,
    publish_time TIMESTAMP WITH TIME ZONE,
    publish_time_inferred BOOLEAN NOT NULL DEFAULT FALSE,
    first_collected_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_collected_at TIMESTAMP WITH TIME ZONE NOT NULL,
    content_version INTEGER NOT NULL DEFAULT 1,
    reading_status VARCHAR(32) NOT NULL DEFAULT 'UNREAD',
    favorite BOOLEAN NOT NULL DEFAULT FALSE,
    archived BOOLEAN NOT NULL DEFAULT FALSE,
    lock_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_article_url_hash UNIQUE(url_hash),
    CONSTRAINT fk_article_source FOREIGN KEY(source_id) REFERENCES crawl_source(id),
    CONSTRAINT ck_article_version CHECK(content_version >= 1)
);
CREATE INDEX idx_article_source ON article(source_id);
CREATE INDEX idx_article_publish ON article(publish_time);

CREATE TABLE crawl_task_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    original_url VARCHAR(2048) NOT NULL,
    normalized_url VARCHAR(2048),
    url_hash CHAR(64),
    status VARCHAR(32) NOT NULL,
    article_id BIGINT,
    retry_count INTEGER NOT NULL DEFAULT 0,
    error_code VARCHAR(64),
    error_message VARCHAR(1000),
    started_at TIMESTAMP WITH TIME ZONE,
    finished_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_item_task FOREIGN KEY(task_id) REFERENCES crawl_task(id) ON DELETE CASCADE,
    CONSTRAINT fk_item_article FOREIGN KEY(article_id) REFERENCES article(id),
    CONSTRAINT uk_task_item_url UNIQUE(task_id, url_hash)
);
