CREATE TABLE source_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id BIGINT NOT NULL,
    rule_version INTEGER NOT NULL,
    list_selector VARCHAR(500) NOT NULL,
    link_selector VARCHAR(500) NOT NULL,
    title_selector VARCHAR(500) NOT NULL,
    content_selector VARCHAR(500) NOT NULL,
    author_selector VARCHAR(500),
    publish_time_selector VARCHAR(500),
    date_pattern VARCHAR(128),
    remove_selectors CLOB NOT NULL DEFAULT '',
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_source_rule_version UNIQUE(source_id, rule_version),
    CONSTRAINT fk_rule_source FOREIGN KEY(source_id) REFERENCES crawl_source(id) ON DELETE CASCADE,
    CONSTRAINT ck_rule_version CHECK(rule_version >= 1)
);
CREATE INDEX idx_rule_source_enabled ON source_rule(source_id, enabled);

ALTER TABLE article ADD COLUMN content_html CLOB;
ALTER TABLE article ADD COLUMN content_text CLOB;
ALTER TABLE article ADD COLUMN word_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE article ADD COLUMN reading_minutes INTEGER NOT NULL DEFAULT 0;
