ALTER TABLE article ADD COLUMN content_fingerprint CHAR(64);
ALTER TABLE article ADD COLUMN quality_score INTEGER NOT NULL DEFAULT 0;
ALTER TABLE article ADD COLUMN review_status VARCHAR(32) NOT NULL DEFAULT 'PENDING_REVIEW';
ALTER TABLE article ADD COLUMN source_level VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN';
ALTER TABLE article ADD COLUMN evidence_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE article ADD COLUMN assessment_warnings CLOB NOT NULL DEFAULT '';
ALTER TABLE article ADD CONSTRAINT ck_article_quality CHECK(quality_score BETWEEN 0 AND 100);

CREATE INDEX idx_article_review_quality ON article(review_status, quality_score);
CREATE INDEX idx_article_fingerprint ON article(content_fingerprint);

CREATE TABLE article_topic_rel (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id BIGINT NOT NULL,
    topic_id BIGINT NOT NULL,
    match_score INTEGER NOT NULL,
    match_reason VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_article_topic UNIQUE(article_id, topic_id),
    CONSTRAINT fk_article_topic_article FOREIGN KEY(article_id) REFERENCES article(id) ON DELETE CASCADE,
    CONSTRAINT fk_article_topic_topic FOREIGN KEY(topic_id) REFERENCES topic(id),
    CONSTRAINT ck_article_topic_score CHECK(match_score BETWEEN 0 AND 100)
);
CREATE INDEX idx_article_topic_topic ON article_topic_rel(topic_id, match_score);
