CREATE TABLE tag (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_name VARCHAR(64) NOT NULL,
    color VARCHAR(16) NOT NULL DEFAULT '#64748B',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_tag_name UNIQUE(tag_name)
);

CREATE TABLE article_tag_rel (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_article_tag UNIQUE(article_id, tag_id),
    CONSTRAINT fk_article_tag_article FOREIGN KEY(article_id) REFERENCES article(id) ON DELETE CASCADE,
    CONSTRAINT fk_article_tag_tag FOREIGN KEY(tag_id) REFERENCES tag(id) ON DELETE CASCADE
);
CREATE INDEX idx_article_tag_tag ON article_tag_rel(tag_id, article_id);

CREATE TABLE article_note (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id BIGINT NOT NULL,
    note_content CLOB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_article_note UNIQUE(article_id),
    CONSTRAINT fk_article_note_article FOREIGN KEY(article_id) REFERENCES article(id) ON DELETE CASCADE
);

CREATE INDEX idx_article_reading_state ON article(reading_status, archived, favorite, publish_time);
