ALTER TABLE crawl_task ADD COLUMN cancel_requested BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE collection_schedule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id BIGINT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    interval_minutes INTEGER NOT NULL DEFAULT 60,
    next_run_at TIMESTAMP WITH TIME ZONE,
    last_run_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_schedule_source UNIQUE(source_id),
    CONSTRAINT fk_schedule_source FOREIGN KEY(source_id) REFERENCES crawl_source(id) ON DELETE CASCADE,
    CONSTRAINT ck_schedule_interval CHECK(interval_minutes BETWEEN 1 AND 10080)
);
CREATE INDEX idx_schedule_due ON collection_schedule(enabled, next_run_at);

CREATE TABLE backup_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    backup_name VARCHAR(256) NOT NULL,
    relative_path VARCHAR(1000) NOT NULL,
    size_bytes BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_backup_name UNIQUE(backup_name)
);
