package com.example.knowledgecollector.application.security;
import com.example.knowledgecollector.application.common.PageResult;import com.example.knowledgecollector.application.exception.BusinessRuleException;import com.example.knowledgecollector.application.exception.ConflictException;import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.util.Locale;
@Service public class UserService {
 private final UserGateway gateway;private final BCryptPasswordEncoder passwords=new BCryptPasswordEncoder(12);public UserService(UserGateway gateway){this.gateway=gateway;}
 public PageResult<UserView> list(String keyword,int page,int size){int safeSize=Math.max(1,Math.min(size,100)),safePage=Math.max(0,page);long total=gateway.count(keyword);return new PageResult<>(gateway.list(keyword,safePage*safeSize,safeSize),safePage,safeSize,total,(int)Math.ceil(total/(double)safeSize),"id,desc");}
 public UserView get(long id){return gateway.get(id);}public UserCredentials credentials(String username){return gateway.findCredentials(normalize(username)).orElse(null);}
 @Transactional public UserView create(String actor,String username,String displayName,String password,String role,boolean enabled){validatePassword(password);String key=normalize(username);if(gateway.findCredentials(key).isPresent())throw new ConflictException("USER-DUPLICATE","用户名已存在");long id=gateway.create(key,required(displayName,"显示名称不能为空"),passwords.encode(password),role(role),enabled);gateway.audit(actor,"USER_CREATE","APP_USER",String.valueOf(id),"创建用户 "+key,"{\"role\":\""+role(role)+"\",\"enabled\":"+enabled+"}");return gateway.get(id);}
 @Transactional public UserView update(String actor,long id,String displayName,String role,boolean enabled){UserView value=gateway.update(id,required(displayName,"显示名称不能为空"),role(role),enabled);gateway.audit(actor,"USER_UPDATE","APP_USER",String.valueOf(id),"更新用户 "+value.username(),"{\"role\":\""+value.role()+"\",\"enabled\":"+enabled+"}");return value;}
 @Transactional public void resetPassword(String actor,long id,String password){validatePassword(password);gateway.updatePassword(id,passwords.encode(password));gateway.audit(actor,"USER_PASSWORD_RESET","APP_USER",String.valueOf(id),"管理员重置用户密码","{}");}
 @Transactional public void changePassword(String username,String current,String next){UserCredentials u=credentials(username);if(u==null||!passwords.matches(current,u.passwordHash()))throw new BusinessRuleException("PASSWORD-CURRENT-INVALID","当前密码不正确");validatePassword(next);gateway.updatePassword(u.id(),passwords.encode(next));gateway.audit(username,"PASSWORD_CHANGE","APP_USER",String.valueOf(u.id()),"用户修改自己的密码","{}");}
 public void recordLogin(long id){gateway.recordLogin(id);}public boolean passwordMatches(String raw,String hash){return passwords.matches(raw,hash);}
 @Transactional public boolean initializeAdmin(String username,String password){if(gateway.count(null)>0)return false;if(username==null||username.isBlank()||password==null||password.isBlank())throw new IllegalStateException("首次启动必须设置 KNOWLEDGE_COLLECTOR_INITIAL_ADMIN_USERNAME 和 KNOWLEDGE_COLLECTOR_INITIAL_ADMIN_PASSWORD");create("SYSTEM",username,"系统管理员",password,"ADMIN",true);return true;}
 private void validatePassword(String value){if(value==null||value.length()<12||!value.matches(".*[A-Z].*")||!value.matches(".*[a-z].*")||!value.matches(".*\\d.*"))throw new BusinessRuleException("PASSWORD-WEAK","密码至少12位，并包含大写字母、小写字母和数字");}private static String normalize(String s){return s==null?"":s.trim().toLowerCase(Locale.ROOT);}private static String role(String r){String v=r==null?"USER":r.toUpperCase(Locale.ROOT);if(!v.equals("USER")&&!v.equals("ADMIN"))throw new BusinessRuleException("USER-ROLE-INVALID","角色只能是 USER 或 ADMIN");return v;}private static String required(String v,String m){if(v==null||v.isBlank())throw new BusinessRuleException("USER-FIELD-EMPTY",m);return v.trim();}
}
